version: "3"
services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#  db:
#    image: postgres:16.0-alpine
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: url_shorter
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - base

volumes:
  redis_data:

networks:
  base:
    driver: bridge
